name: cours_flutter_update_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  updat: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "icons/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "icons/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true
